on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
 # Generate a matrix with a directories which have changed files
 code-coverage:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
 
    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: dotnet build
      working-directory: ${{ inputs.source }}
      run: |
        dotnet restore
        dotnet build -c 'Release' -p 'any'
    
    - name: dotnet test
      working-directory: ${{ inputs.source }}
      run: |
        dotnet test -c 'Release' --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md