//HintName: FooDto.g.cs
// <auto-generated />
using System.Collections.Generic;
using FluentValidation;


public sealed partial record FooDto
{
    internal sealed partial class Validator : AbstractValidator<FooDto>
    {
        public Validator() 
        {
            FooDto.AddValidation(this);
        }
    }
}
