on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
 # Generate a matrix with a directories which have changed files
  code-coverage:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.configuration.outputs.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read Configuration
        id: configuration
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: sln.build.yml
          dotnet-version: '"dotnet-version"'
          services: '"services"[]'

      - name: Display Configuration
        run: |
          echo "${{ toJSON(steps.configuration.outputs) }}"

  matrix-build:
    needs: code-coverage
    uses: spencerr/workflow-tests/.github/workflows/reusable-workflow.yml@checks
    strategy:
      matrix:
        service: ${{ fromJSON(needs.code-coverage.outputs.services) }}
    with:
      solution-directory: ${{ matrix.service.solution-directory }}
      service-project: ${{ matrix.service.service-project }}
      service-name: ${{ matrix.service.name }}
      unit-tests: ${{ matrix.service.unit-tests }}
      integration-tests: ${{ matrix.service.integration-tests }}
      dotnet-version: ${{ matrix.service.dotnet-version }}