on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
 # Generate a matrix with a directories which have changed files
 code-coverage:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Read Solution Configuration
      id: configuration
      uses: the-coding-turtle/ga-yaml-parser@v0.1.2
      with:
        file: './sln.build.yml'

    - name: Read Configuration V2
      id: configuration2
      uses: CumulusDS/get-yaml-paths-action@v1.0.1
      with:
        file: sln.build.yml
        dotnet-version: '"dotnet-version"'
        service-projects: '"service-projects"[]'

    - name: Display read-yaml output
      run: |
        echo "${{ toJSON(steps.configuration2.outputs) }}"
        echo "Service Projects: ${{ toJSON(steps.configuration2.outputs.service-projects) }}"
        echo "${{ toJSON(steps.configuration.outputs) }}"
        echo "dotnet version: ${{ steps.configuration.outputs.dotnet-version }}"
        echo "node version: ${{ steps.configuration.outputs.node-version }}"

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ steps.configuration.outputs.dotnet-version }}

    - name: Setup Node
      uses: actions/setup-node@v3
      if: steps.configuration.outputs.node-version != ''
      with:
        node-version: ${{ steps.configuration.outputs.node-version }}

    - name: dotnet build
      working-directory: ${{ inputs.source }}
      run: |
        projects='${{ steps.configuration2.outputs.service-projects }}'
        for project in $(echo "${projects}" | jq -r '.[]');  do
          dotnet build $project -c 'Release' -p 'any'
        done

    - name: dotnet build
      working-directory: ${{ inputs.source }}
      run: |
        dotnet restore
        dotnet build -c 'Release' -p 'any'

    - name: dotnet test
      working-directory: ${{ inputs.source }}
      run: |
        dotnet test -c 'Release' --no-build \
          --logger "trx;LogFileName=dotnet-test.trx" \
          --results-directory ./coverage \
          --collect:"XPlat Code Coverage"

    - name: Code Coverage - Create Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: success() || failure()
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Code Coverage - Create Cobertura Report
      if: success() || failure()
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage/**/coverage.cobertura.xml \
          -targetdir:${{github.workspace}}/code-coverage \
          -reporttypes:'MarkdownSummaryGithub'

    - name: Code Coverage - Add PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request' && (success() || failure())
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Code Coverage - Add TRX Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Coverage
        path: coverage/dotnet-test.trx
        reporter: dotnet-trx

    - name: Summary - Write Basic Code Coverage
      if: success() || failure()
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Summary - Write Cobertura Report
      if: success() || failure()
      run: cat code-coverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY    